DROP PROCEDURE IF EXISTS SP_INENVIARNOTIFICACION;
DELIMITER $$
CREATE PROCEDURE SP_INENVIARNOTIFICACION(
					IN pnIdUsuario INT)
SP:BEGIN

       INSERT INTO enviar_notificacion(user_id)
       VALUES(pnIdUsuario);
        
END $$
DELIMITER ;
/*
CALL SP_INENVIARNOTIFICACION(1);
*/