DROP PROCEDURE IF EXISTS SP_INTIPOACCION;
DELIMITER $$
CREATE PROCEDURE SP_INTIPOACCION(
					IN pcAccion VARCHAR(45)
                    )
SP:BEGIN
       INSERT INTO tipo_accion(Accion)
       VALUES (pcAccion);
END $$
DELIMITER ;
/*
CALL SP_INTIPOACCION('AGREGAR');
*/